export type Option = {
    id: number;
    name?: string;
    title?: string;
    label?: string;
    slug?: string;
    code?: string;
    status?: string;
    program_id?: number;
    project_id?: number;
    service_stream_id?: number;
    province?: { id: number; name: string } | null;
    project?: { id: number; name: string } | null;
    pathway?: { id: number; name: string } | null;
    first_name?: string;
    last_name?: string;
    surname?: string;
    email?: string;
    training_venue_address?: string;
    latest_published_version?: { id: number; version_number: number; status: string } | null;
};

export type Readiness = {
    ready: boolean;
    status: string;
    checks: Array<{ field: string; label: string; passes: boolean; message: string; action?: string }>;
    errors: Array<{ field: string; message: string }>;
};

export type Offering = {
    id: number;
    service_stream_id: number;
    institution_id?: number | null;
    program_id?: number | null;
    project_id?: number | null;
    project_location_id?: number | null;
    requirement_template_id?: number | null;
    service_pathway_id?: number | null;
    service_pathway_version_id?: number | null;
    owner_staff_id?: number | null;
    facilitator_id?: number | null;
    name: string;
    opportunity_type: string;
    status: string;
    description?: string | null;
    delivery_channel?: string | null;
    delivery_mode?: string | null;
    target_audience?: string | null;
    province?: string | null;
    municipality?: string | null;
    official_url?: string | null;
    external_provider?: string | null;
    contact_reference?: string | null;
    public_slug?: string | null;
    public_title?: string | null;
    public_summary?: string | null;
    public_help_text?: string | null;
    is_active: boolean;
    is_published: boolean;
    published_at?: string | null;
    archived_at?: string | null;
    opens_on?: string | null;
    closes_on?: string | null;
    capacity?: number | null;
    display_order?: number;
    notes?: string | null;
    metadata?: Record<string, string> | null;
    service_stream?: Option | null;
    institution?: Option | null;
    program?: Option | null;
    project?: Option | null;
    project_location?: Option | null;
    requirement_template?: Option | null;
    owner_staff?: Option | null;
    facilitator?: Option | null;
    readiness: Readiness;
    publish_readiness: Readiness;
    historical_references: string[];
    audit_events?: Array<{ id: number; event_type: string; properties: Record<string, unknown>; created_at: string }>;
};

export type OfferingOptions = {
    serviceStreams: Option[];
    institutions: Option[];
    programs: Option[];
    projects: Option[];
    projectLocations: Option[];
    templates: Option[];
    servicePathways: Option[];
    servicePathwayVersions: Option[];
    staffOwners: Option[];
    facilitators: Option[];
};
