<?php

return [
    'guard' => 'web',

    'domains' => [
        'beneficiaries',
        'organization',
        'stakeholders',
        'facilitators',
        'human-resources',
        'assets',
        'programs',
        'projects',
        'business-development',
        'task-management',
        'marketing',
        'finance',
        'staff',
        'leave',
        'events',
        'settings',
        'attendance',
        'governance',
        'committees',
        'meetings',
        'resolutions',
        'policies',
        'compliance',
        'funding',
        'donors',
        'grants',
        'volunteers',
        'procurement',
        'monitoring-evaluation',
        'risk-management',
        'public-benefit-organisation',
        'reporting',
        'members',
        'geography',
        'human-capital',
        'qualifications',
        'skills',
        'employment',
        'placements',
        'partnerships',
        'outcomes',
        'service-delivery',
        'intelligence',
        'citizen-access',
    ],

    'department_domain_map' => [
        'technical' => ['organization', 'projects', 'programs', 'assets', 'task-management', 'events'],
        'marketing' => ['organization', 'beneficiaries', 'stakeholders', 'facilitators', 'programs', 'task-management', 'events', 'marketing'],
        'admin' => ['organization', 'staff', 'human-resources', 'leave', 'settings', 'task-management', 'finance', 'events'],
        'finance' => ['organization', 'finance', 'settings', 'task-management', 'events'],
        'business development' => ['organization', 'beneficiaries', 'stakeholders', 'projects', 'programs', 'business-development', 'task-management', 'events'],
        'governance' => ['organization', 'governance', 'committees', 'meetings', 'resolutions', 'policies', 'reporting'],
        'compliance' => ['organization', 'compliance', 'reporting', 'public-benefit-organisation'],
        'programme management' => ['organization', 'programs', 'projects', 'beneficiaries', 'volunteers', 'monitoring-evaluation', 'reporting', 'placements', 'partnerships', 'outcomes', 'service-delivery', 'citizen-access'],
        'funding' => ['organization', 'funding', 'donors', 'grants', 'reporting'],
        'human capital' => ['organization', 'members', 'geography', 'human-capital', 'qualifications', 'skills', 'employment', 'reporting'],
        'strategy' => ['organization', 'reporting', 'intelligence'],
        'default' => ['organization', 'leave', 'settings', 'task-management'],
    ],
];
